# Where Used: https://github.com/search?q=name+path%3A%2F.github+filename%3Alabels.yml&type=Code&ref=advsearch&l=&l=
#
# GH Action https://github.com/crazy-max/ghaction-github-labeler
# Based on: https://github.com/crazy-max/ghaction-github-labeler/blob/master/.github/labels.yml
# Style Guide: https://gist.github.com/KyleKing/729914c4c88c8de8bcb11f7e978d24cc
- name: "Needs Discussion"
  color: "ff5722"
  description: "Ticket needs discussion and prioritization"
- name: "Type: Bug"
  color: "d73a4a"
  description: "Something isn't working"
  from_name: "bug"
- name: "Type: Maintenance"
  color: "c5def5"
  description: "Chore including refactor, build/dep, CI, perf"
- name: "Type: Idea"
  color: "fbca04"
  description: "General Idea/Concept that could become a feature request"
- name: "Type: Feature"
  color: "0075ca"
  description: "A new feature request"
  from_name: "enhancement"
