---
name: Setup Action
description: Run "poetry install"

inputs:
  os:
    required: true
  poetry-version:
    required: true
    default: 1.1.14
  python-version:
    required: true

env:
  POETRY_VIRTUALENVS_IN_PROJECT: true
  POETRY_NO_INTERACTION: 1

runs:
  using: composite
  steps:
    - name: Install Poetry ${{ inputs.poetry-version }}
      run: pipx install poetry==${{ inputs.poetry-version }}
    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: poetry
    - uses: actions/cache@v2
      id: cache
      with:
        path: .nox
        # yamllint disable-line rule:line-length
        key: ${{inputs.os}}-${{inputs.python-version}}-${{hashFiles('**/poetry.lock')}}
    - name: Install Project and Dependencies
      run: |
        poetry install -E dev -E lint -E test -E commitizen_legacy
      shell: bash
