---
name: Setup Action
description: Run "poetry install"

inputs:
  os:
    default: ubuntu-22.04
  poetry-version:
    default: 1.6.1
  python-version:
    required: true

env:
  POETRY_VIRTUALENVS_IN_PROJECT: true
  POETRY_NO_INTERACTION: 1

runs:
  using: composite
  steps:
    - id: variable-setup
      run: |
        echo "pipx-home=$PIPX_HOME" >> $GITHUB_OUTPUT
        echo "pipx-bin-dir=$PIPX_BIN_DIR" >> $GITHUB_OUTPUT
        echo "python-version=$(echo '${{ inputs.python-version }}' | awk -F. '{print $1"."$2}')" >> $GITHUB_OUTPUT

    # https://pypa.github.io/pipx/how-pipx-works
    - name: Cache pipx
      id: cache-pipx
      uses: actions/cache@v3
      with:
        path: |
          ${{ steps.variable-setup.outputs.pipx-home }}
          ${{ steps.variable-setup.outputs.pipx-bin-dir }}
        key: pipx-poetry-${{ inputs.poetry-version }}
    - name: Install Poetry ${{ inputs.poetry-version }}
      if: steps.cache-pipx.outputs.cache-hit != 'true'
      run: pipx install poetry==${{ inputs.poetry-version }}
      shell: bash

    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: poetry

    - name: Cache .nox
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/.nox
        key: nox-${{ inputs.os }}-${{ steps.variable-setup.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Poetry Debug Info
      run: |-
        poetry debug info
        poetry config --list
      shell: bash

    - name: Install Project and Dependencies
      run: |-
        poetry install -E ddict -E doc -E flake8 -E lint -E nox -E pylint -E stale -E tags -E test -E types
      shell: bash
