---
name: Setup Action
description: Install requested pipx dependencies, configure the system python, and install poetry and the package dependencies

inputs:
  os:
    default: ubuntu-latest
  pipx-packages:
    default: ""
  poetry-version:
    default: 1.8.3
  python-version:
    required: true

env:
  POETRY_VIRTUALENVS_IN_PROJECT: true
  POETRY_NO_INTERACTION: 1

runs:
  using: composite
  steps:
    - name: Install Poetry ${{ inputs.poetry-version }} and '${{ inputs.pipx-packages }}'
      run: |
        for tool in "poetry==${{ inputs.poetry-version }}" ${{ inputs.pipx-packages }}; do
          pipx install $tool
        done
      shell: bash

    - name: Debug pipx
      run: |
        pipx ensurepath
        pipx list
      shell: bash

    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: poetry

    - name: Poetry Debug Info
      run: |
        poetry debug info
        poetry config --list
      shell: bash

    - name: Install Project and Minimum Subset of Dependencies
      run: |
        poetry install && poetry run calcipy-pack pack.install-extras
      shell: bash
