---
name: Setup Action
description: Install requested uvx dependencies, configure the system python, and install poetry and the package dependencies

inputs:
  os:
    description: OS Version
    default: ubuntu-latest
  python-tools:
    description: List of Python packages installed as CLI tools
    default: ""
  uv-version:
    description: Astral/uv version
    default: 0.4.20
  poetry-version:
    description: poetry version
    default: 1.8.3
  python-version:
    description: Python version
    required: true

env:
  POETRY_VIRTUALENVS_IN_PROJECT: true
  POETRY_NO_INTERACTION: 1

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: ${{ inputs.uv-version }}

    - name: Install Poetry ${{ inputs.poetry-version }} and '${{ inputs.python-tools }}'
      run: |
        for tool in "poetry==${{ inputs.poetry-version }}" ${{ inputs.python-tools }}; do
          uv tool install $tool
        done
      shell: bash

    - name: Debug UV
      run: |
        uv cache dir
        uv tool list
        uv tool update-shell
      shell: bash

    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: poetry

    - name: Debug Poetry
      run: |
        poetry debug info
        poetry config --list
      shell: bash

    - name: Install Project and Minimum Subset of Dependencies
      run: |
        poetry install && poetry run calcipy-pack pack.install-extras
      shell: bash
