---
name: Setup Action
description: Install requested uvx dependencies, configure the system python, and install uv and the package dependencies

inputs:
  os:
    description: OS Version
    default: ubuntu-latest
  python-tools:
    description: List of Python packages installed as CLI tools by uv
    default: ""
  uv-version:
    description: Astral/uv version
    default: 0.4.30
  python-version:
    description: Python version
    required: true

runs:
  using: composite
  steps:
    - name: Install 'uv==%{{ inputs.uv-version }}'
      uses: astral-sh/setup-uv@v3
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: true

    - name: Install '${{ inputs.python-tools }}'
      if: ${{ inputs.python-tools }}
      run: |
        for tool in ${{ inputs.python-tools }}; do
          uv tool install $tool
        done
      shell: bash

    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Project and Minimum Subset of Dependencies
      run: uv sync --all-extras
      shell: bash
