# yamllint disable-file
# Answer file maintained by Copier for: https://github.com/KyleKing/calcipy_template
# Check into version control. Edit by re-running copier and changing responses to the questions
_commit: 0.5.3
_src_path: gh:KyleKing/calcipy_template
author_email: dev.act.kyle@gmail.com
author_name: Kyle King
author_username: kyleking
cname: calcipy.kyleking.me
codecov_token: d414dacb-5b8d-4c0b-94e1-42fe8393187d
copyright_date: '2021'
doc_dir: docs
install_extras: -E dev -E lint -E test -E commitizen_legacy
package_name_py: calcipy
project_description: Python package to simplify development. Includes functionality
  for task running, testing, linting, documenting, and more
project_name: calcipy
repository_namespace: kyleking
repository_provider: https://github.com
