# yamllint disable-file
# Answer file maintained by Copier for: https://github.com/KyleKing/calcipy_template
# Check into version control. Edit by re-running copier and changing responses to the questions
_commit: 0.13.3
_src_path: gh:KyleKing/calcipy_template
author_email: dev.act.kyle@gmail.com
author_name: Kyle King
author_username: kyleking
cname: calcipy.kyleking.me
copyright_date: '2021'
development_branch: main
doc_dir: docs
include_adrs: false
install_extras: -E dev -E lint -E test -E commitizen_legacy
minimum_python: 3.8.4
package_name_py: calcipy
project_description: Python package to simplify development. Includes functionality
    for task running, testing, linting, documenting, and more
project_name: calcipy
repository_namespace: kyleking
repository_provider: https://github.com
