---
# Docs: https://pre-commit.com/#new-hooks
# Can be tested with:
#   pre-commit try-repo . --verbose --all-files --hook-stage push
#   pre-commit try-repo . tags --verbose --all-files --hook-stage push
#   pre-commit try-repo . lint-fix --verbose --all-files
- id: copier-forbidden-files
  name: Copier Forbidden Files
  entry: |
    Found copier update rejection files; review them and remove them
    (https://copier.readthedocs.io/en/stable/updating/)
  language: fail
  files: \.rej$
- id: lint-fix
  additional_dependencies: [".[lint]"]
  description: "Run ruff and apply fixes"
  entry: calcipy-lint lint.fix
  language: python
  minimum_pre_commit_version: 2.9.2
  name: Lint-Fix
  require_serial: true
  types: [python]
- id: tags
  additional_dependencies: [".[tags]"]
  description: "Create a `CODE_TAG_SUMMARY.md` with a table for TODO- and FIXME-style code comments"
  entry: calcipy-tags tags
  language: python
  minimum_pre_commit_version: 2.9.2
  name: Tags
  pass_filenames: false
  require_serial: true
  stages: [pre-push]
