version: 0.0.{build}

image: Visual Studio 2019

environment:
  # Set Python version here. See: https://www.appveyor.com/docs/windows-images-software/#pythonor
  # For linux: https://www.appveyor.com/docs/linux-images-software/
  matrix:
    - PYTHON: C:/Python36
    - PYTHON: C:/Python39

  # To encrypt password, in the AppVeyor Account, go to "Settings" -> "Encrypt YAML"

cache:
  - '.venv'

init:
- cmd: ECHO $cd%
- cmd: DIR
# Choose Python version
- cmd: set PATH=%PYTHON%\Scripts;%PYTHON%;%PATH%
- cmd: python --version
# Install pipx to manage poetry installation
- cmd: python -m pip install pipx
# - cmd: python -m pipx ensurepath
- cmd: set PATH=%USERPROFILE%\.local\bin;%PATH%
- cmd: ECHO %PATH%
# Install poetry
- cmd: python -m pipx install poetry
- cmd: poetry config --list
- cmd: poetry config virtualenvs.in-project true

install:
- cmd: poetry install -E dev -E lint -E test -E cz_legacy

test_script:
- cmd: poetry run doit run test

deploy_script:
- cmd: ECHO "Deploying..."

on_success:
- cmd: ECHO "On Success..."

on_failure:
- cmd: ECHO "On Error..."
- cmd: poetry run doit

artifacts:
  # PLANNED: Can multiple files be specified or need a zip?
  - path: releases/tests/*
  - path: releases/tests/test_report.html
