version: 0.0.{build}

image:
  - Visual Studio 2019
  - Ubuntu

environment:
  # Set Python version here. See: https://www.appveyor.com/docs/windows-images-software/#pythonor
  # For linux: https://www.appveyor.com/docs/linux-images-software/
  matrix:
    - PYTHON: C:/Python37
    # - PYTHON: C:/Python39

  # To encrypt password, in the AppVeyor Account, go to "Settings" -> "Encrypt YAML"

cache:
  - '.venv'

build: off

# Specify commands specific to platform (cmd-Windows/sh-Linux/None-Both)
install:
# Choose Python version
- cmd: set PATH=%PYTHON%/Scripts;%PYTHON%;%PATH%
- sh: PATH=$PYTHON/Scripts;$PYTHON;$PATH
- python --version
# Install pipx to manage poetry installation
- python -m pip install pipx
# - python -m pipx ensurepath
- cmd: set PATH=%USERPROFILE%/.local/bin;%PATH%
- sh: PATH=~/.local/bin;$PATH
- cmd: echo %PATH%
- sh: echo $PATH
# Install poetry
- python -m pipx install poetry
- poetry config --list
- poetry config virtualenvs.in-project true
# Install project-specific dependencies and extras
- poetry install -E dev -E lint -E test -E commitizen_legacy

test_script:
- poetry run doit run test

deploy_script:
- echo "Deploying..."

on_success:
- echo "On Success..."

on_failure:
- echo "On Error..."
- poetry run doit

artifacts:
  # PLANNED: Can multiple files be specified or need a zip?
  - path: releases/tests/*
  - path: releases/tests/test_report.html
