---
site_name: calcipy
site_author: Kyle King
site_url: https://calcipy.kyleking.me
site_description: calcipy project documentation
repo_name: kyleking/calcipy
repo_url: https://github.com/kyleking/calcipy
edit_uri: edit/main/docs
docs_dir: docs
site_dir: releases/site

theme:
  name: material
  palette:
    - scheme: default
      accent: green
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - toc.autohide

plugins:
  - search
  - git-revision-date

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      linenums: true
  - def_list
  - extra
  - fenced_code
  - footnotes
  - markdown_include.include
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - smarty
  - tables
  - toc:
      permalink: ⚓︎
      toc_depth: 5
