site_name: calcipy
site_author: Kyle King
site_description: calcipy project documentation
repo_name: KyleKing/calcipy
repo_url: https://github.com/KyleKing/calcipy
edit_uri: edit/main/docs
docs_dir: docs
site_dir: releases/site

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - toc.autohide

plugins:
  - search
  - mkdocstrings:
      watch:
        - calcipy

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - markdown_include.include
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - toc:
      permalink: ⚓︎
      toc_depth: 3
