# Answer file maintained by Copier for: https://github.com/KyleKing/calcipy_template
# Check into version control. Edit by re-running copier and changing responses to the questions
_commit: 0.0.6
_src_path: gh:KyleKing/calcipy_template
author_email: dev.act.kyle@gmail.com
author_name: Kyle King
author_username: kyleking
codecov_token: NA
copyright_date: '2021'
doc_dir: docs_custom
install_extras: null
package_name_py: test_project
project_description: This project is testing the functionality of copier_calcipy
project_name: Test Project
repository_namespace: kyleking
repository_provider: https://github.com
