"""
# Dash_Dev ([Github](https://github.com/KyleKing/dash_dev))

Python package to simplify development. Includes functionality for task running, testing, linting, documenting, and more

Note: the package name is a misnomer and is not specific to Plotly/Dash projects (and I haven't thought of a better replacement yet). If you want to build Plotly/Dash applications, see [dash_charts](https://github.com/KyleKing/dash_charts)

## Quick Start

<!-- TODO: Replace with CookieCutter Instructions -->

Add to a poetry project in `pyproject.toml`:

```toml
[tool.poetry.dev-dependencies.dash_dev]
git = \"https://github.com/KyleKing/dash_dev.git\"
branch = \"main\"
```

Then copy the [`https://github.com/KyleKing/dash_dev/blob/main/dodo.py`](https://github.com/KyleKing/dash_dev/blob/main/dodo.py) file into your project and call with `poetry run doit`

If you have any questions, please [open an issue on Github](https://github.com/KyleKing/dash_dev/issues/new)

## Where Used

- [KyleKing/dash_charts](https://github.com/KyleKing/dash_charts)
- [KyleKing/PiAlarm](https://github.com/KyleKing/PiAlarm)
- [KyleKing/Kitsu_Library_Availability](https://github.com/KyleKing/Kitsu_Library_Availability)
- [KyleKing/Goodreads_Library_Availability](https://github.com/KyleKing/Goodreads_Library_Availability) - *Planned*

## Test Coverage

<!-- COVERAGE -->

| File | Statements | Missing | Excluded | Coverage |
| --: | --: | --: | --: | --: |
| `dash_dev/__init__.py` | 11 | 0 | 0 | 100.0% |
| `dash_dev/conftest.py` | 23 | 3 | 0 | 87.0% |
| `dash_dev/doit_helpers/__init__.py` | 0 | 0 | 0 | 100.0% |
| `dash_dev/doit_helpers/base.py` | 51 | 14 | 0 | 72.5% |
| `dash_dev/doit_helpers/dev.py` | 45 | 45 | 0 | 0.0% |
| `dash_dev/doit_helpers/doc.py` | 136 | 78 | 0 | 42.6% |
| `dash_dev/doit_helpers/doit_globals.py` | 54 | 2 | 0 | 96.3% |
| `dash_dev/doit_helpers/lint.py` | 81 | 19 | 0 | 76.5% |
| `dash_dev/doit_helpers/test.py` | 40 | 13 | 0 | 67.5% |
| `dash_dev/log_helpers.py` | 24 | 5 | 0 | 79.2% |
| `dash_dev/registered_tasks.py` | 6 | 6 | 0 | 0.0% |
| `dash_dev/tag_collector.py` | 86 | 34 | 0 | 60.5% |

Generated on: 2020-11-14T11:50:47.015891

<!-- /COVERAGE -->
"""  # noqa

__version__ = '0.0.2'
__pkg_name__ = 'dash_dev'

import logging
import sys
from pathlib import Path

from loguru import logger

logger.disable(__pkg_name__)

LOG_DIR = Path(__file__).resolve().parent / '.logs'
"""Output directory for log files."""
LOG_DIR.mkdir(exist_ok=True)

LOGGER_CONFIG = {
    'handlers': [
        {'sink': sys.stdout,
         'backtrace': True, 'diagnose': False},
        {'sink': LOG_DIR / 'debug-{time}.jsonl', 'mode': 'w', 'level': logging.DEBUG, 'serialize': True,
         'rotation': '1 hour', 'backtrace': True, 'diagnose': True},
        {'sink': LOG_DIR / 'debug-{time}.log', 'mode': 'w', 'level': logging.DEBUG,
         'rotation': '1 hour', 'backtrace': True, 'diagnose': True},
    ],
    'extra': {'package': __pkg_name__},
}
"""Loguru configuration. Loguru is deactivated for this package by default and must be activated.

```py
from this_package import __pkg__name__

logger.configure(**LOGGER_CONFIG)
logger.enable(__pkg__name__)

# You can continue to import and enable additional packages as needed, but you should only call configure once
```

"""

# =============== Above is Auto-Generated by dash_dev. User content goes below ===============
