"""dash_dev."""

__version__ = '0.0.3'
__pkg_name__ = 'dash_dev'

import logging
import sys
from pathlib import Path

from loguru import logger

logger.disable(__pkg_name__)

LOG_DIR = Path(__file__).resolve().parent / '.logs'
"""Output directory for log files."""

LOGGER_CONFIG = {
    'handlers': [
        {'sink': sys.stdout,
         'backtrace': True, 'diagnose': False},
        {'sink': LOG_DIR / 'debug-{time}.jsonl', 'mode': 'w', 'level': logging.DEBUG, 'serialize': True,
         'rotation': '1h', 'backtrace': True, 'diagnose': True},
        {'sink': LOG_DIR / 'debug-{time}.log', 'mode': 'w', 'level': logging.DEBUG,
         'rotation': '1h', 'backtrace': True, 'diagnose': True},
    ],
    'extra': {'package': __pkg_name__},
}
"""Loguru configuration. Loguru is deactivated for this package by default and must be activated.

```py
from this_package import __pkg__name__

logger.configure(**LOGGER_CONFIG)
logger.enable(__pkg__name__)

# You can continue to import and enable additional packages as needed, but you should only call configure once
```

"""

# =============== Above is Auto-Generated by dash_dev. User content goes below ===============

LOG_DIR.mkdir(exist_ok=True)
