"""calcipy."""

from loguru import logger

__version__ = '0.2.0a0'
__pkg_name__ = 'calcipy'

logger.disable(__pkg_name__)

# =============== Above is Auto-Generated by calcipy. User content goes below ===============
