"""Collect code tags and output for review in a single location."""

from beartype import beartype

from ..code_tag_collector import write_code_tag_file
from .base import debug_task
from .doit_globals import DG, DoitTask


@beartype
def task_collect_code_tags() -> DoitTask:
    """Create a summary file with all of the found code tags.

    Returns:
        DoitTask: doit task

    """
    kwargs = {
        'path_tag_summary': DG.tags.path_code_tag_summary,
        'paths_source': DG.meta.paths,
        'base_dir': DG.meta.path_project,
        'regex_compiled': DG.tags.compile_issue_regex(),
        'header': f'# Task Summary\n\nAuto-Generated by `{DG.meta.pkg_name}`',
        'tag_order': DG.tags.tags,
    }
    return debug_task([(write_code_tag_file, (), kwargs)])
