---
# Docs: https://github.com/marketplace/actions/github-labeler
name: github_labeler

# Will only be run each push or PR merge to the main branch
"on":
  push:
    branches: [main]
    paths: [.github/labels.yml, .github/workflows/labeler.yml]
  workflow_dispatch: null # For manual runs

permissions:
  # Issues and related comments, assignees, labels, and milestones.
  issues: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: false
          dry-run: false
