# Docs: https://gist.github.com/thatisuday/b3b6096457e64cdfa20796315ed29fbd

name: github_labeler

# Change back to main to reduce number of times run
on:
  push:
    branches:
      - dev/development

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: false
          dry-run: true
